## PROBLEM STATEMENT-
perform Linear Regression for 50_Startups 


In [1]:
## Importing Packages

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

import warnings
warnings.filterwarnings("ignore")

In [2]:
## Reading the data

In [6]:
strt50 = pd.read_csv("E:\\deeksha\\python\\data\\50_Startups.csv")

In [7]:
strt50.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [9]:
strt50.rename(columns={'R&D Spend': 'RnD_Spend',  'Marketing Spend': 'Marketing_Spend'}, inplace=True)

In [10]:
strt50.head()

RnD_Spend  Administration  Marketing_Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [11]:
strt50.describe()

RnD_Spend  Administration  Marketing_Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [12]:
strt50.tail()

RnD_Spend  Administration  Marketing_Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [13]:
strt50.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RnD_Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing_Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [14]:
strt50.corr()

RnD_Spend  Administration  Marketing_Spend    Profit
RnD_Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing_Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [15]:
strt50.drop(columns=['Administration'], inplace=True)

In [16]:
strt50

RnD_Spend  Marketing_Spend       State     Profit
0   165349.20        471784.10    New York  192261.83
1   162597.70        443898.53  California  191792.06
2   153441.51        407934.54     Florida  191050.39
3   144372.41        383199.62    New York  182901.99
4   142107.34        366168.42     Florida  166187.94
5   131876.90        362861.36    New York  156991.12
6   134615.46        127716.82  California  156122.51
7   130298.13        323876.68     Florida  155752.60
8   120542.52        311613.29    New York  152211.77
9   123334.88        304981.62  California  149759.96
10  101913.08        229160.95     Florida  146121.95
11  100671.96        249744.55  California  144259.40
12   93863.75        249839.44     Florida  141585.52
13   91992.39        252664.93  California  134307.35
14  119943.24        256512.92     Florida  132602.65
15  114523.61        261776.23    New York  129917.04
16   78013.11        264346.06  California  126992.93
17   94657.16        282574.31    New York  125370.37
18   91749.16        294919.57     Florida  124266.90
19   86419.70             0.00    New York  122776.86
20   76253.86        298664.47  California  118474.03
21   78389.47        299737.29    New York  111313.02
22   73994.56        303319.26     Florida  110352.25
23   67532.53        304768.73     Florida  108733.99
24   77044.01        140574.81    New York  108552.04
25   64664.71        137962.62  California  107404.34
26   75328.87        134050.07     Florida  105733.54
27   72107.60        353183.81    New York  105008.31
28   66051.52        118148.20     Florida  103282.38
29   65605.48        107138.38    New York  101004.64
30   61994.48         91131.24     Florida   99937.59
31   61136.38         88218.23    New York   97483.56
32   63408.86         46085.25  California   97427.84
33   55493.95        214634.81     Florida   96778.92
34   46426.07        210797.67  California   96712.80
35   46014.02        205517.64    New York   96479.51
36   28663.76        201126.82     Florida   90708.19
37   44069.95        197029.42  California   89949.14
38   20229.59        185265.10    New York   81229.06
39   38558.51        174999.30  California   81005.76
40   28754.33        172795.67  California   78239.91
41   27892.92        164470.71     Florida   77798.83
42   23640.93        148001.11  California   71498.49
43   15505.73         35534.17    New York   69758.98
44   22177.74         28334.72  California   65200.33
45    1000.23          1903.93    New York   64926.08
46    1315.46        297114.46     Florida   49490.75
47       0.00             0.00  California   42559.73
48     542.05             0.00    New York   35673.41
49       0.00         45173.06  California   14681.40

In [19]:
X = strt50.iloc[:,0:3]

In [20]:
X.head()

RnD_Spend  Marketing_Spend       State
0  165349.20        471784.10    New York
1  162597.70        443898.53  California
2  153441.51        407934.54     Florida
3  144372.41        383199.62    New York
4  142107.34        366168.42     Florida

In [21]:
## using 1 hot encoding to convert categorical data into numeric data

In [22]:
X = pd.get_dummies(X, columns=['State'], drop_first=True)

In [23]:
y = strt50["Profit"]

In [24]:
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [25]:
X

RnD_Spend  Marketing_Spend  State_Florida  State_New York
0   165349.20        471784.10              0               1
1   162597.70        443898.53              0               0
2   153441.51        407934.54              1               0
3   144372.41        383199.62              0               1
4   142107.34        366168.42              1               0
5   131876.90        362861.36              0               1
6   134615.46        127716.82              0               0
7   130298.13        323876.68              1               0
8   120542.52        311613.29              0               1
9   123334.88        304981.62              0               0
10  101913.08        229160.95              1               0
11  100671.96        249744.55              0               0
12   93863.75        249839.44              1               0
13   91992.39        252664.93              0               0
14  119943.24        256512.92              1               0
15  114523.61        261776.23              0               1
16   78013.11        264346.06              0               0
17   94657.16        282574.31              0               1
18   91749.16        294919.57              1               0
19   86419.70             0.00              0               1
20   76253.86        298664.47              0               0
21   78389.47        299737.29              0               1
22   73994.56        303319.26              1               0
23   67532.53        304768.73              1               0
24   77044.01        140574.81              0               1
25   64664.71        137962.62              0               0
26   75328.87        134050.07              1               0
27   72107.60        353183.81              0               1
28   66051.52        118148.20              1               0
29   65605.48        107138.38              0               1
30   61994.48         91131.24              1               0
31   61136.38         88218.23              0               1
32   63408.86         46085.25              0               0
33   55493.95        214634.81              1               0
34   46426.07        210797.67              0               0
35   46014.02        205517.64              0               1
36   28663.76        201126.82              1               0
37   44069.95        197029.42              0               0
38   20229.59        185265.10              0               1
39   38558.51        174999.30              0               0
40   28754.33        172795.67              0               0
41   27892.92        164470.71              1               0
42   23640.93        148001.11              0               0
43   15505.73         35534.17              0               1
44   22177.74         28334.72              0               0
45    1000.23          1903.93              0               1
46    1315.46        297114.46              1               0
47       0.00             0.00              0               0
48     542.05             0.00              0               1
49       0.00         45173.06              0               0

In [26]:
## splitting the data into two parts (train ,test)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,random_state=110)

In [28]:
X_train.shape

(40, 4)

In [29]:
y_test

19    122776.86
41     77798.83
14    132602.65
12    141585.52
31     97483.56
18    124266.90
36     90708.19
40     78239.91
13    134307.35
24    108552.04
Name: Profit, dtype: float64

## Multi Linear Regression

In [30]:
model_lr = LinearRegression()

In [31]:
model_lr.fit(X_train ,y_train)

LinearRegression()

In [32]:
model_lr.intercept_

45432.51703677449

In [33]:
model_lr.coef_

array([ 8.18825665e-01,  2.65845207e-02, -1.44493886e+02,  3.95792635e+02])

In [34]:
model_lr.predict(X_test)

array([116590.97796605,  72499.83691003, 150319.89940841, 128787.93240716,
        98233.58602626, 128254.88549557,  74105.50560173,  73570.99048343,
       127475.22299465, 112651.03632111])

In [35]:
ypred_test = model_lr.predict(X_test)

In [38]:
ypred_train = model_lr.predict(X_train)

In [36]:
from sklearn.metrics import r2_score

In [39]:
R2_train = r2_score(y_train,ypred_train)

In [40]:
R2_test = r2_score(y_test, ypred_test)

print(R2_train,R2_test)

In [42]:
## importing MinMaxScaler

In [41]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scaler = MinMaxScaler()

In [44]:
scaler.fit_transform(X)

array([[1.        , 1.        , 0.        , 1.        ],
       [0.98335946, 0.94089337, 0.        , 0.        ],
       [0.92798459, 0.8646636 , 1.        , 0.        ],
       [0.87313643, 0.81223513, 0.        , 1.        ],
       [0.85943772, 0.77613557, 1.        , 0.        ],
       [0.797566  , 0.76912588, 0.        , 1.        ],
       [0.81412828, 0.27071031, 0.        , 0.        ],
       [0.7880179 , 0.68649342, 1.        , 0.        ],
       [0.72901786, 0.66049977, 0.        , 1.        ],
       [0.74590551, 0.64644319, 0.        , 0.        ],
       [0.61635061, 0.48573267, 1.        , 0.        ],
       [0.60884455, 0.52936195, 0.        , 0.        ],
       [0.56766982, 0.52956308, 1.        , 0.        ],
       [0.55635219, 0.53555202, 0.        , 0.        ],
       [0.72539353, 0.54370828, 1.        , 0.        ],
       [0.69261666, 0.55486446, 0.        , 1.        ],
       [0.47180821, 0.56031151, 0.        , 0.        ],
       [0.57246821, 0.59894835,

In [45]:
Scaled_X_train = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
Scaled_X_train.head()

RnD_Spend  Marketing_Spend  State_Florida  State_New York
0   0.447505         0.642920            1.0             0.0
1   0.000000         0.000000            0.0             0.0
2   0.608845         0.529362            0.0             0.0
3   0.873136         0.812235            0.0             1.0
4   0.788018         0.686493            1.0             0.0

In [46]:
Scaled_X_test = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)
Scaled_X_test.head()

RnD_Spend  Marketing_Spend  State_Florida  State_New York
0   0.522650         0.000000            0.0             1.0
1   0.168691         0.348614            1.0             0.0
2   0.725394         0.543708            1.0             0.0
3   0.567670         0.529563            1.0             0.0
4   0.369741         0.186989            0.0             1.0

In [48]:
# Building Model

In [47]:
model_lr2 = LinearRegression()

In [49]:
## Fitting train data in the Model

In [51]:
model_lr2.fit(Scaled_X_train ,y_train)

LinearRegression()

In [52]:
model_lr2.intercept_

45432.517036773934

In [53]:
ypred_test2 = model_lr2.predict(Scaled_X_test)

In [54]:
ypred_train2 = model_lr2.predict(Scaled_X_train)

In [55]:
from sklearn.metrics import r2_score

In [56]:
scaled_R2_train = r2_score(y_train,ypred_train2)

In [57]:
scaled_R2_test = r2_score(y_test, ypred_test2)

In [58]:
print(scaled_R2_train,scaled_R2_test)

0.9588111729958975 0.8170261487225507


In [59]:
ypred_test2

array([116590.97796606,  72499.83691003, 150319.89940842, 128787.93240716,
        98233.58602626, 128254.88549557,  74105.50560172,  73570.99048343,
       127475.22299465, 112651.03632111])

In [60]:
ypred_test

array([116590.97796605,  72499.83691003, 150319.89940841, 128787.93240716,
        98233.58602626, 128254.88549557,  74105.50560173,  73570.99048343,
       127475.22299465, 112651.03632111])